<?php

namespace DAO\TicketingBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTicketsCount(\DateTime $date)
    {
        return $this->createQueryBuilder('t')
            ->select('COUNT(t)')
            ->where('t.dateResa = :date')
            ->setParameter('date', $date)
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
