<?php

namespace DAO\TicketingBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTicketsCount(\DateTime $date)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('COUNT(t)')
            ->from($this->_entityName, 't')
            ->where('t.dateResa = :date')
            ->setParameter('date', $date)
        ;

        $query = $queryBuilder->getQuery();

        $results = $query->getSingleScalarResult();

        return $results;
    }
}
