dao_ticketing_home:
    path:     /home
    defaults: { _controller: DAOTicketingBundle:Ticket:index }

dao_ticketing_date:
    path:     /date
    defaults: { _controller: DAOTicketingBundle:Ticket:registerDate }

dao_ticketing_modifyTicket:
    path:     /modifyTicket/{id}
    defaults: { _controller: DAOTicketingBundle:Ticket:modifyTicket }

dao_ticketing_register:
    path:     /register/{id}/{nbTickets}/{current}
    defaults: { _controller: DAOTicketingBundle:Ticket:registerVisitor }

dao_ticketing_modifyVisitor:
    path:     /modifyVisitor/{id}
    defaults: { _controller: DAOTicketingBundle:Ticket:modifyVisitor }
    
dao_ticketing_summery:
    path:     /summery/{id}
    defaults: { _controller: DAOTicketingBundle:Ticket:registerSummery }

dao_ticketing_home_payment:
    path:     /home_payment/{id}
    defaults: { _controller: DAOTicketingBundle:Ticket:paymentIndex }

dao_ticketing_payment:
    path:     /payment/{id}
    defaults: { _controller: DAOTicketingBundle:Ticket:payment }

dao_ticketing_confirming:
    path:     /confirming
    defaults: { _controller: DAOTicketingBundle:Ticket:paymentConfirming }